# Generated by Django 4.1 on 2022-10-02 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='ulr',
            new_name='url',
        ),
    ]
